## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(ltJPpR50wT0oIY9kfOe1Iw==)
      client-secret: ENC(ltJPpR50wT0oIY9kfOe1Iw==)
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
      - '/AlarmInformation'
      - '/eventSubscriptions'
      - '/testSave'

spring:
  datasource:
    #引入druid数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.238:3306/hhsep?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
 
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.hcdz.hk.pojo
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.hk.mapper: debug
#eureka注册配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:2001/eureka,http://localhost:2002/eureka
      
#匹配学校id配置
campus:
  schoolCode:
    ea0de7bdff0a4498b0fe26e849388827: 00000001
    9b33f1c788f04dceb665fa15cfcd8ed6: 00000002
