 ## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(ltJPpR50wT0oIY9kfOe1Iw==)
      client-secret: ENC(ltJPpR50wT0oIY9kfOe1Iw==)
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:


        - '/actuator/**'
        - '/v2/api-docs'
        - '/user/info/*'
        - '/social/info/*'
        - '/mobile/*'
        - '/log/save'
        - '/actuator/**'
        - '/v2/api-docs'
        - '/user/info/**'
        - '/social/info/*'
        - '/mobile/*'
        - '/log/save'

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

#    password: 123456
    url: jdbc:mysql://192.168.0.238:3306/hhsep?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2Mb
      max-request-size: 2Mb

# swagger相关配置,覆盖全局配置
swagger:
  authorization:
    authorization-scope-list:
      - scope: 'server'
        description: 'server all'
      - scope: 'read'
        description: 'read all'
      - scope: 'write'
        description: 'access all'



# Logger Config
logging:
  level:
    com.campus.admin.mapper: debug
