
server:
  port: 3001
  
spring:
  application:
    name: feign
  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?hkdb=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.hcdz.hk.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.hk.mapper: debug  

#向eureka注册中心注册    
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:2001/eureka, http://localhost:2002/eureka
      
#ribbo全局配置，充实参数调整
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000

#启动hystri配置
feign:
  hystrix:
    enabled: true
#配置降级超时时间    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
#暴露hystrix.stream监控端点   
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    